# -*- coding: utf-8 -*-
"""data analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1urwYppUtr5pl8tLf_vi1cZhe125gQNRP
"""

first_data.head(3)

""" 
1.  Number of rows and columns can be found in the following code cells for each data sets
2.  Also, types of each attribute are listed below for first_data
3. Since all datas have similar attributes, there is no need to show each data's attributes' type


 </font>
"""

num_row, num_col = first_data.shape 
print("total number of rows in first_data: {} \ntotal number of columns in first_data: {}".format(num_row, num_col))
print("\nTypes of attributes:\n{}".format(first_data.dtypes))

first_data.isna().sum() / first_data.shape[0]

data_for_artist.head(3)

num_row, num_col = data_for_artist.shape 
print("total number of rows in data_for_artist: {} \ntotal number of columns in data_for_artist: {}".format(num_row, num_col))

data_for_genres.head(2)

num_row, num_col = data_for_genres.shape 
print("total number of rows in data_for_genres: {} \ntotal number of columns in data_for_genres: {}".format(num_row, num_col))

data_for_genres.isna().sum() / data_for_genres.shape[0]

data_for_years.head(2)

num_row, num_col = data_for_years.shape 
print("total number of rows in data_for_years: {} \ntotal number of columns in data_for_years: {}".format(num_row, num_col))

data_for_years.isna().sum() / data_for_years.shape[0]

data_for_wgenres.head(2)

num_row, num_col = data_for_wgenres.shape 
print("total number of rows in data_for_wgenres: {} \ntotal number of columns in data_for_wgenres: {}".format(num_row, num_col))

data_for_wgenres.isna().sum() / data_for_wgenres.shape[0]