# -*- coding: utf-8 -*-
"""song_recommendation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E8adxrAE8NnrnCV5loPGKdOzxC17Q2v8

## Creating a simple song recommendation system

* In this part of the project, we will implement a basic song recommendation program
* To acieve this, we will use manhattan distance to find the KNN of the given song
* After that, we will sort them according to their distance value to our source song
"""

from tqdm import tqdm
recommended_data = first_data

class SpotifyRecommender():
    def __init__(self, rec_data):
        #our class should understand which data to work with
        self.rec_data_ = rec_data
    
    #if we need to change data
    def change_data(self, rec_data):
        self.rec_data_ = rec_data
    
    #function which returns recommendations, we can also choose the amount of songs to be recommended
    def get_recommendations(self, song_name, amount=1):
        distances = []
        #choosing the data for our song
        song = self.rec_data_[(self.rec_data_.name.str.lower() == song_name.lower())].head(1).values[0]
        #dropping the data with our song
        res_data = self.rec_data_[self.rec_data_.name.str.lower() != song_name.lower()]
        for r_song in tqdm(res_data.values):
            dist = 0
            for col in np.arange(len(res_data.columns)):
                #indeces of non-numerical columns
                if not col in [1, 6, 12, 14, 18]:
                    #calculating the manhettan distances for each numerical feature
                    dist = dist + np.absolute(float(song[col]) - float(r_song[col]))
            distances.append(dist)
        res_data['distance'] = distances
        #sorting our data to be ascending by 'distance' feature
        res_data = res_data.sort_values('distance')
        columns = ['artists', 'name']
        return res_data[columns][:amount]

recommend_machine = SpotifyRecommender(recommended_data)

"""* Here are a couple of example runnings"""

recommend_machine.get_recommendations('champagne problems', 5)

recommend_machine.get_recommendations('Girls Like You (feat. Cardi B)', 5)

recommend_machine.get_recommendations('drivers license', 5)